version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: jobportal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: jobportal-backend
    ports:
      - "4444:4444"
    environment:
      - MONGO_URL=mongodb://mongo:27017/jobportal
    depends_on:
      - mongo
    restart: always
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: jobportal-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    working_dir: /app

volumes:
  mongo-data:
